title: Andrew H. Lu
description: Welcome to Andrew's personal website!
permalink: pretty
theme: andrew-jekyll
gh_url: "https://github.com/andrewhlu/web"
collections:
  projects:
    output: true
    permalink: /projects/:path/
  experience:
    output: true
    permalink: /experience/:path/
  awards:
    output: true
    permalink: /awards/:path/